/* eslint-disable */
// Generated by Wrangler by running `wrangler types --include-runtime=false` (hash: 3d6774e142a83360fdb66fc163f30600)
interface __BaseEnv_Env {
  TURSO_DATABASE_URL: string;
  TURSO_AUTH_TOKEN: string;
}
declare namespace Cloudflare {
  interface GlobalProps {
    mainModule: typeof import("./src/worker/index");
  }
  interface Env extends __BaseEnv_Env {}
}
interface Env extends __BaseEnv_Env {}
type StringifyValues<EnvType extends Record<string, unknown>> = {
  [Binding in keyof EnvType]: EnvType[Binding] extends string ? EnvType[Binding] : string;
};
declare namespace NodeJS {
  interface ProcessEnv extends StringifyValues<
    Pick<Cloudflare.Env, "TURSO_DATABASE_URL" | "TURSO_AUTH_TOKEN">
  > {}
}
