/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './react-app/routes/__root'
import { Route as IndexRouteImport } from './react-app/routes/index'
import { Route as AboutRouteImport } from './react-app/routes/about'
import { Route as LoginRouteImport } from './react-app/routes/login'
import { Route as ProfileRouteImport } from './react-app/routes/profile'
import { Route as ActivitiesActivityIdRouteImport } from './react-app/routes/activities.$activityId'
import { Route as ActivitiesActivityIdBookRouteImport } from './react-app/routes/activities.$activityId_.book'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileRoute = ProfileRouteImport.update({
  id: '/profile',
  path: '/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesActivityIdRoute = ActivitiesActivityIdRouteImport.update({
  id: '/activities/$activityId',
  path: '/activities/$activityId',
  getParentRoute: () => rootRouteImport,
} as any)
const ActivitiesActivityIdBookRoute =
  ActivitiesActivityIdBookRouteImport.update({
    id: '/activities/$activityId_/book',
    path: '/activities/$activityId/book',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/activities/$activityId': typeof ActivitiesActivityIdRoute
  '/activities/$activityId/book': typeof ActivitiesActivityIdBookRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/activities/$activityId': typeof ActivitiesActivityIdRoute
  '/activities/$activityId/book': typeof ActivitiesActivityIdBookRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/login': typeof LoginRoute
  '/profile': typeof ProfileRoute
  '/activities/$activityId': typeof ActivitiesActivityIdRoute
  '/activities/$activityId_/book': typeof ActivitiesActivityIdBookRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/login'
    | '/profile'
    | '/activities/$activityId'
    | '/activities/$activityId/book'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/login'
    | '/profile'
    | '/activities/$activityId'
    | '/activities/$activityId/book'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/login'
    | '/profile'
    | '/activities/$activityId'
    | '/activities/$activityId_/book'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  LoginRoute: typeof LoginRoute
  ProfileRoute: typeof ProfileRoute
  ActivitiesActivityIdRoute: typeof ActivitiesActivityIdRoute
  ActivitiesActivityIdBookRoute: typeof ActivitiesActivityIdBookRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile': {
      id: '/profile'
      path: '/profile'
      fullPath: '/profile'
      preLoaderRoute: typeof ProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities/$activityId': {
      id: '/activities/$activityId'
      path: '/activities/$activityId'
      fullPath: '/activities/$activityId'
      preLoaderRoute: typeof ActivitiesActivityIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/activities/$activityId_/book': {
      id: '/activities/$activityId_/book'
      path: '/activities/$activityId/book'
      fullPath: '/activities/$activityId/book'
      preLoaderRoute: typeof ActivitiesActivityIdBookRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  LoginRoute: LoginRoute,
  ProfileRoute: ProfileRoute,
  ActivitiesActivityIdRoute: ActivitiesActivityIdRoute,
  ActivitiesActivityIdBookRoute: ActivitiesActivityIdBookRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
